stages:
  - build
  - deploy
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
variables:
  APP_IMAGE: "registry.gitlab.com/driver_app1/driver-app"
  OPENSHIFT_PROJECT: "yizwshe-dev"

build_and_push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $APP_IMAGE:$CI_COMMIT_SHORT_SHA -f Dockerfile .
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push $APP_IMAGE:$CI_COMMIT_SHORT_SHA
  artifacts:
    name: "web-artifacts"
    paths:
      - build/web
  only:
    - dev
deploy_openshift:
  stage: deploy
  image: quay.io/openshift/origin-cli:latest
  script:
    - echo "$OPENSHIFT_TOKEN" | oc login --token=$(cat -) --server=$OPENSHIFT_SERVER --insecure-skip-tls-verify
    - oc project $OPENSHIFT_PROJECT
    - oc set image deployment/flutter-deployment flutter=$APP_IMAGE:$CI_COMMIT_SHORT_SHA --record
    - oc rollout status deployment/flutter-deployment
  only:
    - dev

