analyzer:
  exclude:
    - test/**
    - build/**
    - .dart_tool/**
    - node_modules/**
    - web/**
    - android/**
    - ios/**
    - windows/**
    - linux/**
    - macos/**
    - scripts/**
    - assets/**
    - example/**
